#!/bin/sh

if [ ! -f /etc/wpa_supplicant.conf ] && [ -f /boot/wpa_supplicant.conf ]; then
    cp /boot/wpa_supplicant.conf /etc/wpa_supplicant.conf
    chmod 600 /etc/wpa_supplicant.conf
fi

if [ -f /etc/wpa_supplicant.conf ]; then
    wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
    sleep 5
    udhcpc -i wlan0
fi