name: Build Buildroot Image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo (external tree)
        uses: actions/checkout@v4

      - name: Checkout Buildroot (2023.11)
        uses: actions/checkout@v4
        with:
          repository: buildroot/buildroot
          path: buildroot
          ref: 2023.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 git unzip bc cpio rsync file

      - name: Build image
        run: |
          cd buildroot
          make BR2_EXTERNAL=../gt7-br2-external raspberrypi4_defconfig
          make

      - name: Upload output images
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-images
          path: buildroot/output/images/

