name: Build Buildroot Image (Pi4) and Upload to SimDash Releases

on:
  push:
    branches: [ main ]
    paths:
      - 'package/**'
      - 'board/**'
      - 'configs/**'
      - '.github/workflows/build.yml'
      - 'kernel-dsi.fragment'
      - 'external.mk'
      - 'external.desc'

  pull_request:
  workflow_dispatch:
    inputs:
      simdash_tag:
        description: 'gt7-simdash tag to use'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIMDASH_TAG: ${{ github.event.inputs.simdash_tag }}

    steps:
      - name: Checkout your repo (external tree)
        uses: actions/checkout@v4
        with:
          path: gt7-br2-external

      - name: Checkout Buildroot (2023.11)
        uses: actions/checkout@v4
        with:
          repository: buildroot/buildroot
          path: buildroot
          ref: 2023.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 git unzip bc cpio rsync file

      - name: Build image for Pi 4
        run: |
          cd buildroot
          make BR2_EXTERNAL=../gt7-br2-external \
               BR2_ROOTFS_OVERLAY="../gt7-br2-external/board/raspberrypi4/overlay" \
               BR2_CONFIG_FRAGMENT_FILES="../gt7-br2-external/buildroot.fragment" \
               SIMDASH_TAG="${SIMDASH_TAG}" \
               raspberrypi4_defconfig
          # override the config.txt path
          ./utils/config --set-str BR2_PACKAGE_RPI_FIRMWARE_CONFIG_FILE ../gt7-br2-external/board/raspberrypi4/config.txt
          make

      - name: Rename image for release
        run: |
          mv buildroot/output/images/sdcard.img buildroot/output/images/sdcard-raspberrypi4.img

      - name: Upload Pi 4 image to SimDash repo "latest" release
        uses: softprops/action-gh-release@v2
        with:
          # repository: chrshdl/gt7-simdash
          tag_name: latest
          name: Latest Build
          files: buildroot/output/images/sdcard-raspberrypi4.img
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.SIMDASH_RELEASE_PAT }}

      - name: Upload output images as artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: images-raspberrypi4
          path: buildroot/output/images/
